services:

  gateway:
    build: ./gateway
    ports:
      - "3001:3000"
    depends_on:
      - user-service
      - product-service
      - redis

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"

  product-service:
    build: ./product-service
    ports:
      - "4002:4002"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
      - "6379:6379"