version: "3.8"

services:

  gateway:
    build: ./gateway
    ports:
      - "3001:3000"
    depends_on:
      - user-service
      - product-service

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"

  product-service:
    build: ./product-service
    ports:
      - "4002:4002"
